variables:
  NUGET_PATH: 'C:\Tools\Nuget\nuget.exe'
  MSBUILD_PATH: 'C:\MSBuildTools\MSBuild\Current\bin\msbuild.exe'
  
stages:
  - build
  - deploy

build_job:
  stage: build
  only:
    - branches
  script:
    - '& "$env:NUGET_PATH" restore'
    - '& "$env:MSBUILD_PATH" /p:Configuration=Release /clp:ErrorsOnly'
    - '& "$env:MSBUILD_PATH" QuoteService.sln /p:Configuration=Release'
  artifacts:
    expire_in: 2 days
    paths:
      - '.\QuoteService\bin\Release\'

deploy_job:
  stage: deploy
  only:
    - branches
  script:
    - 'xcopy /y /s ".\QuoteService\bin\Release\*.*" "C:\QuoteService\bin"'
  dependencies:
    - build_job