variables:
  NUGET_PATH: 'C:\Tools\nuget.exe'
  MSBUILD_PATH: 'C:\MSBuildTools\MSBuild\Current\bin\msbuild.exe'
  
stages:
  - build
  - deploy

build_job:
  stage: build
  only:
    - master
  script:
    - '& "$env:NUGET_PATH" restore'
    - '& "$env:MSBUILD_PATH" /p:Configuration=Release /clp:ErrorsOnly'
  artifacts:
    expire_in: 2 days
    paths:
      - '.\QuoteService\bin\Release\'

deploy_job:
  stage: deploy
  only:
    - master
  script:
    - 'gsutil cp gs://sk_quote_lib/gitlab-cd.ps1 C:/QuoteService/'
    - 'powershell -noexit "& ""C:\QuoteService\gitlab-cd.ps1"""'
  dependencies:
    - build_job