variables:
  NUGET_PATH: 'C:\Tools\nuget.exe'
  MSBUILD_PATH: 'C:\MSBuildTools\MSBuild\Current\bin\msbuild.exe'

  
stages:
  - build
  - test
  - deploy

build_job:
  stage: build
  only:
    - master
  script:
    - '& "$env:NUGET_PATH" restore'
    - '& "$env:MSBUILD_PATH" /p:Configuration=Release /clp:ErrorsOnly'
  artifacts:
    expire_in: 2 days
    paths:
      - '.\QuoteService\bin\Release\'

test_job:
  stage: test
  only:
    - merge_requests
  script:
    -. .\unit-test.ps1
  dependencies:
    - build_job

deploy_job:
  stage: deploy
  only:
    - master
  script:
    - 'gsutil cp gs://quote_vm_ci_cd/gitlab-cd.ps1 C:/QuoteService/'
    - 'powershell -noexit "& ""C:\QuoteService\gitlab-cd.ps1"""'
  dependencies:
    - test_job