variables:
  NUGET_PATH: 'C:\Tools\nuget.exe'
  MSBUILD_PATH: 'C:\MSBuildTools\MSBuild\Current\bin\msbuild.exe'
  
stages:
  - build
  - deploy

build_job:
  stage: build
  only:
    - master
  script:
    - '& "$env:NUGET_PATH" restore'
    - '& "$env:MSBUILD_PATH" /p:Configuration=Release /clp:ErrorsOnly'
  artifacts:
    expire_in: 2 days
    paths:
      - '.\QuoteService\bin\Release\'

deploy_job:
  stage: deploy
  only:
    - master
  script:
    - 'net stop QuoteService'
    - 'sc delete QuoteService'
    - 'xcopy /y /s ".\QuoteService\bin\Release\*.*" "C:\QuoteService\bin"'
    - 'gsutil cp gs://sk_quote_lib/appsettings.json C:/QuoteService/bin/'
    - 'C:\QuoteService\bin\QuoteService.exe install'
    - 'net start QuoteService'
  dependencies:
    - build_job